# Generated by Django 4.1.1 on 2022-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_playlist_songs_author_playlist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(help_text='Descrição do autor', max_length=255, verbose_name='Descrição:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Digite o nome do autor', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(help_text='Descrição da playlist', max_length=255, verbose_name='Descrição:'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Minha playlist', help_text='Digite o nome da playlist', max_length=255, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.TimeField(help_text='Digite o tempo de duração da musica', verbose_name='Duração:'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(help_text='Digite o nome da musica', max_length=255, verbose_name='Nome:'),
        ),
        migrations.DeleteModel(
            name='Playlist_Songs',
        ),
    ]
