# Generated by Django 4.1.1 on 2022-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_author_description_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='cadastros.song'),
        ),
    ]
